org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# NeoForge
neo_version=21.1.77
loader_version_range=[2,)
neo_version_range=[21.1,)

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# Mod
mod_id=hexmotd
mod_name=Hex MOTD
mod_version=1.0.0
mod_group_id=com.kingmihailp.hexmotd
mod_authors=KingMihailP
mod_description=Allows displaying hex colors in the server MOTD.
